<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign In</name>
   <tag></tag>
   <elementGuidId>c1195732-e4fa-4b3a-810c-408068d4592e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.jsx-1859088085.auth-page__content__box__buttons__signin.SignIn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02511744-61bd-4557-b3bf-a8a7de63542c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7a93af7d-556f-4396-b7fe-b5d6925dc75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1859088085 auth-page__content__box__buttons__signin SignIn</value>
      <webElementGuid>db270bb3-0a60-463e-bf3a-bdcf0d19d08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>dce28b13-175b-44ce-84df-15e48dc81363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;transition&quot;]/div[@class=&quot;jsx-1859088085 auth-page&quot;]/div[@class=&quot;jsx-1859088085 auth-page__content&quot;]/form[@class=&quot;jsx-1859088085 auth-page__content__box&quot;]/div[@class=&quot;jsx-1859088085 auth-page__content__box__buttons&quot;]/button[@class=&quot;jsx-1859088085 auth-page__content__box__buttons__signin SignIn&quot;]</value>
      <webElementGuid>4a08659f-7859-46ee-a5d1-26e48ebd2847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0325a03c-7d54-467d-8f82-9d2db9e0e97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>877f8ab2-4a44-459c-afd8-cb010674eb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1859088085 auth-page__content__box__buttons__signin SignIn</value>
      <webElementGuid>a7f2550f-21a5-4588-b27e-ff279b230590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>38eb49b7-65f5-47fe-96b6-00de3d944743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;transition&quot;]/div[@class=&quot;jsx-1859088085 auth-page&quot;]/div[@class=&quot;jsx-1859088085 auth-page__content&quot;]/form[@class=&quot;jsx-1859088085 auth-page__content__box&quot;]/div[@class=&quot;jsx-1859088085 auth-page__content__box__buttons&quot;]/button[@class=&quot;jsx-1859088085 auth-page__content__box__buttons__signin SignIn&quot;]</value>
      <webElementGuid>0e921141-4d18-4f35-9d3d-0eb95acdeb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04d6a2c1-a284-40cb-9677-cf2dfdc7d186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f088e705-c341-407a-bd56-f0ec4c948bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-1859088085 auth-page__content__box__buttons__signin SignIn</value>
      <webElementGuid>4e248ceb-4fe7-4948-8a42-bc1aba29de23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>73d8a589-43e8-466e-9dd0-95507db5d463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;transition&quot;]/div[@class=&quot;jsx-1859088085 auth-page&quot;]/div[@class=&quot;jsx-1859088085 auth-page__content&quot;]/form[@class=&quot;jsx-1859088085 auth-page__content__box&quot;]/div[@class=&quot;jsx-1859088085 auth-page__content__box__buttons&quot;]/button[@class=&quot;jsx-1859088085 auth-page__content__box__buttons__signin SignIn&quot;]</value>
      <webElementGuid>260db866-21b1-4b03-8a7f-b7fc60659983</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>c501a45a-a05f-4686-94c8-3b2c1827522e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/form/div/button</value>
      <webElementGuid>6dd2ecd0-3edc-452a-b47c-e30b8de98b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Your Password?'])[1]/following::button[1]</value>
      <webElementGuid>1587549e-87ca-4975-9e06-abb95af35f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>1b669772-ed4f-47ed-8019-7e68cad77d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or sign in with the following methods'])[1]/preceding::button[1]</value>
      <webElementGuid>edb5b2a5-f61d-467c-84de-5b5c49a23ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In with Facebook'])[1]/preceding::button[1]</value>
      <webElementGuid>a3ae0d7a-8f8f-41eb-8b24-a9adf92bc8d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign In']/parent::*</value>
      <webElementGuid>5a048cbf-9f28-4bf7-83fc-59f951a7b1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>da75b702-631f-4c2a-a087-a6bfdd785073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>ed11c930-f724-4d1f-80ef-11dfd9e3f2ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
